services:
  # Frontend
  - type: web
    name: chat-frontend
    runtime: node
    region: singapore # Optional: defaulting to common region, can be removed
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_USER_SERVICE_URL
        fromService: chat-user-service
        property: url
      - key: NEXT_PUBLIC_CHAT_SERVICE_URL
        fromService: chat-service
        property: url

  # User Service
  - type: web
    name: chat-user-service
    runtime: node
    rootDir: backend/user
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        fromService: chat-redis
        property: connectionString
      - key: RABBITMQ_URL
        sync: false

  # Chat Service
  - type: web
    name: chat-service
    runtime: node
    rootDir: backend/chat
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: USER_SERVICE
        fromService: chat-user-service
        property: url
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false

  # Mail Service
  - type: web
    name: chat-mail-service
    runtime: node
    rootDir: backend/mail
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: RABBITMQ_URL
        sync: false
      - key: USER
        sync: false
      - key: PASS
        sync: false

databases:
  - name: chat-redis
    plan: free # Note: Render Redis Free tier is ephemeral
